import 'dart:typed_data';

import 'package:flutter/material.dart' show Color, Colors;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import 'api_service.dart';

/// Generates a professional cephalometric analysis PDF and triggers a
/// browser download (Flutter Web) or share sheet (mobile).
Future<void> generateClinicalReport({
  required Uint8List imageBytes,
  required List<DiagnosticRow> diagnostics,
  String clinicalSummary = '',
  String patientId = 'PT-XXXXXX',
}) async {
  final pdf = pw.Document(
    title: 'Cephalometric Analysis Report',
    author: 'Ceph AI',
  );

  // ── Decode the JPEG for embedding ─────────────────────────────────────────
  final pdfImage = pw.MemoryImage(imageBytes);

  // ── PDF color palette ──────────────────────────────────────────────────────
  final headerBg = PdfColor.fromHex('1C1C2E');
  final accentTeal = PdfColor.fromHex('00BFA5');
  final accentOrange = PdfColor.fromHex('FF6B35');
  final rowAlt = PdfColor.fromHex('F4F6FA');
  final textDark = PdfColor.fromHex('1C1C2E');
  final textMid = PdfColor.fromHex('555577');

  // ── Date ──────────────────────────────────────────────────────────────────
  final now = DateTime.now();
  final dateStr =
      '${now.day.toString().padLeft(2, '0')}/'
      '${now.month.toString().padLeft(2, '0')}/${now.year}';

  pdf.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(32),
      header: (ctx) =>
          _pageHeader(headerBg, accentTeal, textDark, patientId, dateStr),
      footer: (ctx) => _pageFooter(textMid, ctx),
      build: (ctx) => [
        pw.SizedBox(height: 12),

        // ── Annotated X-ray ─────────────────────────────────────────────────
        pw.Center(
          child: pw.Container(
            constraints: const pw.BoxConstraints(maxHeight: 320),
            decoration: pw.BoxDecoration(
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
              border: pw.Border.all(color: accentTeal, width: 1),
            ),
            child: pw.Image(pdfImage, fit: pw.BoxFit.contain),
          ),
        ),

        pw.SizedBox(height: 20),

        // ── Section heading ──────────────────────────────────────────────────
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
          decoration: pw.BoxDecoration(
            color: accentTeal,
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
          ),
          child: pw.Text(
            'Clinical Diagnostics Report',
            style: pw.TextStyle(
              fontSize: 11,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
            ),
          ),
        ),

        pw.SizedBox(height: 8),

        if (clinicalSummary.isNotEmpty) ...[
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: PdfColor.fromHex('E0F2F1'), // light teal
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
              border: pw.Border.all(color: accentTeal, width: 0.5),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  '🤖 AI Clinical Summary',
                  style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColor.fromHex('00796B'), // darker teal
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  clinicalSummary,
                  style: pw.TextStyle(
                    fontSize: 9,
                    color: textDark,
                    lineSpacing: 1.5,
                  ),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 12),
        ],

        // ── Diagnostics table ────────────────────────────────────────────────
        _diagnosticsTable(
          diagnostics,
          rowAlt,
          accentTeal,
          accentOrange,
          textDark,
          textMid,
        ),

        pw.SizedBox(height: 16),

        // ── Disclaimer ──────────────────────────────────────────────────────
        pw.Container(
          padding: const pw.EdgeInsets.all(10),
          decoration: pw.BoxDecoration(
            color: PdfColor.fromHex('F0F0F8'),
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
          ),
          child: pw.Text(
            'DISCLAIMER: This report is generated by an AI-assisted system and '
            'is intended for clinical reference only. All measurements should be '
            'verified by a licensed orthodontist or dentofacial orthopaedist '
            'before use in treatment planning.',
            style: pw.TextStyle(
              fontSize: 7.5,
              color: textMid,
              fontStyle: pw.FontStyle.italic,
            ),
          ),
        ),
      ],
    ),
  );

  // ── Trigger download / print dialog ───────────────────────────────────────
  await Printing.layoutPdf(
    onLayout: (_) async => pdf.save(),
    name: 'CephAI_Report_$patientId.pdf',
  );
}

// ── Header widget ──────────────────────────────────────────────────────────

pw.Widget _pageHeader(
  PdfColor bg,
  PdfColor accent,
  PdfColor textDark,
  String patientId,
  String date,
) => pw.Container(
  padding: const pw.EdgeInsets.fromLTRB(14, 10, 14, 10),
  decoration: pw.BoxDecoration(
    color: bg,
    borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
  ),
  child: pw.Row(
    children: [
      pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Cephalometric Analysis Report',
            style: pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
            ),
          ),
          pw.SizedBox(height: 3),
          pw.Text(
            'Powered by Ceph AI  |  AI-Assisted Clinical Decision Support',
            style: pw.TextStyle(fontSize: 8, color: PdfColors.grey300),
          ),
        ],
      ),
      pw.Spacer(),
      pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        children: [
          pw.Text(
            'Patient ID: $patientId',
            style: pw.TextStyle(
              fontSize: 9,
              color: accent,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 3),
          pw.Text(
            'Date: $date',
            style: pw.TextStyle(fontSize: 8, color: PdfColors.grey300),
          ),
        ],
      ),
    ],
  ),
);

// ── Footer widget ──────────────────────────────────────────────────────────

pw.Widget _pageFooter(PdfColor textMid, pw.Context ctx) => pw.Container(
  alignment: pw.Alignment.center,
  margin: const pw.EdgeInsets.only(top: 8),
  child: pw.Text(
    'Page ${ctx.pageNumber} of ${ctx.pagesCount}  |  Generated by Ceph AI',
    style: pw.TextStyle(fontSize: 7.5, color: textMid),
  ),
);

// ── Diagnostics data table ─────────────────────────────────────────────────

pw.Widget _diagnosticsTable(
  List<DiagnosticRow> rows,
  PdfColor rowAlt,
  PdfColor teal,
  PdfColor orange,
  PdfColor textDark,
  PdfColor textMid,
) {
  const headers = ['Parameter', 'Value', 'Reference', 'Diff', 'Comment'];
  const colWidths = [0.18, 0.10, 0.12, 0.10, 0.50];

  pw.Widget headerCell(String txt) => pw.Padding(
    padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
    child: pw.Text(
      txt,
      style: pw.TextStyle(
        fontSize: 8.5,
        fontWeight: pw.FontWeight.bold,
        color: PdfColors.white,
      ),
    ),
  );

  pw.Widget dataCell(String txt, {PdfColor? color, bool bold = false}) =>
      pw.Padding(
        padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
        child: pw.Text(
          txt,
          style: pw.TextStyle(
            fontSize: 8,
            color: color ?? textDark,
            fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
          ),
          overflow: pw.TextOverflow.clip,
        ),
      );

  // Build column widths as fractions of full width
  final totalWidth = PdfPageFormat.a4.availableWidth - 64;
  final widths = colWidths
      .map((f) => pw.FixedColumnWidth(totalWidth * f))
      .toList();

  return pw.Table(
    columnWidths: {for (var i = 0; i < widths.length; i++) i: widths[i]},
    border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
    children: [
      // Header row
      pw.TableRow(
        decoration: pw.BoxDecoration(color: PdfColor.fromHex('252540')),
        children: headers.map(headerCell).toList(),
      ),
      // Data rows
      ...rows.asMap().entries.map((entry) {
        final i = entry.key;
        final row = entry.value;
        final diffColor = row.isAbnormal ? orange : teal;
        final bg = i.isOdd ? rowAlt : PdfColors.white;

        return pw.TableRow(
          decoration: pw.BoxDecoration(color: bg),
          children: [
            dataCell(row.parameter, bold: true),
            dataCell(row.value),
            dataCell(row.reference, color: textMid),
            dataCell(row.diff, color: diffColor, bold: true),
            dataCell(row.comment, color: row.isAbnormal ? orange : textMid),
          ],
        );
      }),
    ],
  );
}
